# Generated by Django 3.2.9 on 2021-11-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagerequest', '0002_remove_packagerequest_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
    ]
