# Generated by Django 3.2.9 on 2021-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagerequest', '0003_alter_packagerequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='package_Main_Img',
            field=models.ImageField(default='XYZ', upload_to='images/'),
        ),
    ]
